### ISSUE TITLE
Choose initial programming language

### ISSUE THREAD

**Issue by oddstr13** [themetadb/metametametadb#2]
- [ ] Python
- [ ] Other

**Comment by oddstr13** [comment]
My suggestion is to go for Python > 3.6, using the following libraries & tools:

 - [FastAPI][fastapi]
   FastAPI is a modern, fast (high-performance), web framework for building APIs with Python 3.6+ based on standard Python type hints.
 - [SQLAlchemy][sqlalchemy]
   SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL.
 - [Coverage.py][coverage]
   Coverage.py measures code coverage, typically during test execution. It uses the code analysis tools and tracing hooks provided in the Python standard library to determine which lines are executable, and which have been executed.
 - [pytest][pytest]
   The pytest framework makes it easy to write small tests, yet scales to support complex functional testing for applications and libraries.
 - [Mypy][mypy]
   Mypy is an optional static type checker for Python that aims to combine the benefits of dynamic (or "duck") typing and static typing.
 - [flake8][flake8]
   flake8 is a python tool that glues together pep8, pyflakes, mccabe, and third-party plugins to check the style and quality of some python code.


[fastapi]: https://fastapi.tiangolo.com/
[sqlalchemy]: https://www.sqlalchemy.org/
[coverage]: https://coverage.readthedocs.io/
[pytest]: https://docs.pytest.org/en/latest/
[mypy]: http://mypy-lang.org/
[flake8]: https://flake8.pycqa.org/

**Comment by heyhippari** [comment]
I vote for Python as well (mostly because I know it).

@oddstr13 's stack proposal seems good and aligns with what I'd have proposed myself.

**Comment by nielsvanvelzen** [comment]
I think we can close this issue since @oddstr13 already started on the backend using Python.
